'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/navbar/navbar";
import {Client} from '@/lib/client'

// import { ApolloWrapper } from "@/lib/apollo-wrapper";

import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';

// import { NhostClient, NhostProvider } from '@nhost/nextjs'
// import { NhostApolloProvider } from '@nhost/react-apollo'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// const nhost = new NhostClient({
//   subdomain: 'eu-central-1',
//   region: 'llajjjtabvtxypmlbqdv'
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-auto transition ease-in-out delay-150 duration-500`} suppressHydrationWarning={true}>
            <Navbar/>
            <ApolloProvider client={Client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
